/*
 For license information please see main.js.LICENSE.txt */
(function(u){var r=window.AmazonUIPageJS||window.P,I=r._namespace||r.attributeErrors,p=I?I("PRIVCONAssets@centralized-prompting",""):r;p.guardFatal?p.guardFatal(u)(p,window):p.execute(function(){u(p,window)})})(function(u,r,I){function p(g,r,p){r in g?Object.defineProperty(g,r,{value:p,enumerable:!0,configurable:!0,writable:!0}):g[r]=p;return g}var t="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(g){return typeof g}:function(g){return g&&"function"===typeof Symbol&&g.constructor===
Symbol&&g!==Symbol.prototype?"symbol":typeof g};u.when("3p-promise").register("@amzn/consent-orchestration-client-sdk",function(g){var p;(function(){function u(a){var b;(b=function(a){if(Array.isArray(a))return N(a)}(a))||(b="undefined"!=typeof Symbol&&null!=a[Symbol.iterator]||null!=a["@@iterator"]?Array.from(a):void 0);if(!(a=b||function(a,b){if(a){if("string"==typeof a)return N(a,b);var c={}.toString.call(a).slice(8,-1);return"Object"===c&&a.constructor&&(c=a.constructor.name),"Map"===c||"Set"===
c?Array.from(a):"Arguments"===c||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(c)?N(a,b):void 0}}(a)))throw new TypeError("Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");return a}function N(a,b){(null==b||b>a.length)&&(b=a.length);for(var e=0,c=Array(b);e<b;e++)c[e]=a[e];return c}function m(){for(var a=arguments.length,b=Array(a),e=0;e<a;e++)b[e]=arguments[e];return b.filter(function(a){return a}).join(".")}
function x(){for(var a=[],b=arguments.length,e=Array(b),c=0;c<b;c++)e[c]=arguments[c];e.forEach(function(b){Array.isArray(b)?a.push.apply(a,u(b)):a.push(b)});b=a.filter(function(a){return"string"==typeof a&&""!==a.trim()}).map(function(a){return a.replace(/,/g,"-")});return m.apply(void 0,u(b))}function h(a){return h="function"==typeof Symbol&&"symbol"==t(Symbol.iterator)?function(a){return"undefined"===typeof a?"undefined":t(a)}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&
a!==Symbol.prototype?"symbol":"undefined"===typeof a?"undefined":t(a)},h(a)}function ia(a,b){for(var e=0;e<b.length;e++){var c=b[e];c.enumerable=c.enumerable||!1;c.configurable=!0;"value"in c&&(c.writable=!0);Object.defineProperty(a,O(c.key),c)}}function G(a,b,e){return(b=O(b))in a?Object.defineProperty(a,b,{value:e,enumerable:!0,configurable:!0,writable:!0}):a[b]=e,a}function O(a){a:if("object"==h(a)&&a){var b=a[Symbol.toPrimitive];if(void 0!==b){a=b.call(a,"string");if("object"!=h(a))break a;throw new TypeError("@@toPrimitive must return a primitive value.");
}a=String(a)}return"symbol"==h(a)?a:a+""}function P(a,b){(null==b||b>a.length)&&(b=a.length);for(var e=0,c=Array(b);e<b;e++)c[e]=a[e];return c}function I(a){return a>Date.now()-Q.promptTimeWindow*X}function w(a){var b=Date.now();return a>=Q.promptsUntilCooldown?b+Q.readCooldownDuration*X:void 0}function v(a){return v="function"==typeof Symbol&&"symbol"==t(Symbol.iterator)?function(a){return"undefined"===typeof a?"undefined":t(a)}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&
a!==Symbol.prototype?"symbol":"undefined"===typeof a?"undefined":t(a)},v(a)}function R(a,b){var e=Object.keys(a);if(Object.getOwnPropertySymbols){var c=Object.getOwnPropertySymbols(a);b&&(c=c.filter(function(b){return Object.getOwnPropertyDescriptor(a,b).enumerable}));e.push.apply(e,c)}return e}function C(a){for(var b=1;b<arguments.length;b++){var e=null!=arguments[b]?arguments[b]:{};b%2?R(Object(e),!0).forEach(function(b){var c,d=e[b];a:if("object"==v(b)&&b){var ba=b[Symbol.toPrimitive];if(void 0!==
ba){b=ba.call(b,"string");if("object"!=v(b))break a;throw new TypeError("@@toPrimitive must return a primitive value.");}b=String(b)}(c="symbol"==v(b)?b:b+"")in a?Object.defineProperty(a,c,{value:d,enumerable:!0,configurable:!0,writable:!0}):a[c]=d}):Object.getOwnPropertyDescriptors?Object.defineProperties(a,Object.getOwnPropertyDescriptors(e)):R(Object(e)).forEach(function(b){Object.defineProperty(a,b,Object.getOwnPropertyDescriptor(e,b))})}return a}function S(a,b){var e,c=H(a,b),d=(e=c.prompts,
[Date.now()].concat(function(a){if(Array.isArray(a))return P(a)}(e)||function(a){if("undefined"!=typeof Symbol&&null!=a[Symbol.iterator]||null!=a["@@iterator"])return Array.from(a)}(e)||function(a,b){if(a){if("string"==typeof a)return P(a,b);var c={}.toString.call(a).slice(8,-1);return"Object"===c&&a.constructor&&(c=a.constructor.name),"Map"===c||"Set"===c?Array.from(a):"Arguments"===c||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(c)?P(a,b):void 0}}(e)||function(){throw new TypeError("Invalid attempt to spread non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");
}()).filter(I).sort(function(a,b){return b-a}).slice(0,Q.promptsUntilCooldown));U(a,{principal:c.principal,prompts:d,defer:w(d.length)},b)}function H(a,b){var e,c,d,k,g=a.id(),f={principal:g,prompts:[]};try{var K=a.get(ca);if(!K)return f;var q=JSON.parse(r.atob(K));return b.emitCount(m(b.appName,l.SERVICE,l.STORE,l.READ)),q.principal===g||(e=g,c=null!==(k=c=q.principal)&&void 0!==k?k:"",(e=null!==(d=e)&&void 0!==d?d:"").length!=c.length&&e.startsWith(c))?C(C({},q),{},{principal:g}):f}catch(da){return b.emitCount(m(b.appName,
l.SERVICE,l.STORE,l.READ,l.ERROR)),f}}function U(a,b,e){try{var c=r.btoa(JSON.stringify(b));a.set(ca,c);e.emitCount(m(e.appName,l.SERVICE,l.STORE,l.WRITE))}catch(aa){e.emitCount(m(e.appName,l.SERVICE,l.STORE,l.WRITE,l.ERROR))}}function z(a){return z="function"==typeof Symbol&&"symbol"==t(Symbol.iterator)?function(a){return"undefined"===typeof a?"undefined":t(a)}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":"undefined"===typeof a?"undefined":
t(a)},z(a)}function y(a){var b="function"==typeof Map?new Map:void 0;return y=function(a){function c(){return function(a,b,c){if(D())return Reflect.construct.apply(null,arguments);var e=[null];e.push.apply(e,b);e=new (a.bind.apply(a,e));return c&&d(e,c.prototype),e}(a,arguments,f(this).constructor)}if(null===a||!function(a){try{return-1!==Function.toString.call(a).indexOf("[native code]")}catch(k){return"function"==typeof a}}(a))return a;if("function"!=typeof a)throw new TypeError("Super expression must either be null or a function");
if(void 0!==b){if(b.has(a))return b.get(a);b.set(a,c)}return c.prototype=Object.create(a.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}}),d(c,a)},y(a)}function D(){try{var a=!Boolean.prototype.valueOf.call(Reflect.construct(Boolean,[],function(){}))}catch(b){}return(D=function(){return!!a})()}function d(a,b){return d=Object.setPrototypeOf?Object.setPrototypeOf.bind():function(a,b){return a.__proto__=b,a},d(a,b)}function f(a){return f=Object.setPrototypeOf?Object.getPrototypeOf.bind():
function(a){return a.__proto__||Object.getPrototypeOf(a)},f(a)}function q(a){return q="function"==typeof Symbol&&"symbol"==t(Symbol.iterator)?function(a){return"undefined"===typeof a?"undefined":t(a)}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":"undefined"===typeof a?"undefined":t(a)},q(a)}function Y(){function a(a,b,c){return Object.defineProperty(a,b,{value:c,enumerable:!0,configurable:!0,writable:!0}),a[b]}function b(a,b,d,e){b=Object.create((b&&
b.prototype instanceof c?b:c).prototype);e=new p(e||[]);return w(b,"_invoke",{value:K(a,d,e)}),b}function e(a,b,c){try{return{type:"normal",arg:a.call(b,c)}}catch(la){return{type:"throw",arg:la}}}function c(){}function d(){}function k(){}function f(b){["next","throw","return"].forEach(function(c){a(b,c,function(a){return this._invoke(c,a)})})}function l(a,b){function c(d,n,L,V){d=e(a[d],a,n);if("throw"!==d.type){var E=d.arg;return(d=E.value)&&"object"==q(d)&&u.call(d,"__await")?b.resolve(d.__await).then(function(a){c("next",
a,L,V)},function(a){c("throw",a,L,V)}):b.resolve(d).then(function(a){E.value=a;L(E)},function(a){return c("throw",a,L,V)})}V(d.arg)}var d;w(this,"_invoke",{value:function(a,n){function e(){return new b(function(b,d){c(a,n,b,d)})}return d=d?d.then(e,e):e()}})}function K(a,b,c){var d=C;return function(n,L){if(d===G)throw Error("Generator is already running");if(d===z){if("throw"===n)throw L;return{value:h,done:!0}}c.method=n;for(c.arg=L;;){if(n=c.delegate)if(n=m(n,c)){if(n===F)continue;return n}if("next"===
c.method)c.sent=c._sent=c.arg;else if("throw"===c.method){if(d===C)throw d=z,c.arg;c.dispatchException(c.arg)}else"return"===c.method&&c.abrupt("return",c.arg);d=G;n=e(a,b,c);if("normal"===n.type){if(d=c.done?z:H,n.arg===F)continue;return{value:n.arg,done:c.done}}"throw"===n.type&&(d=z,c.method="throw",c.arg=n.arg)}}}function m(a,b){var c=b.method,d=a.iterator[c];if(d===h)return b.delegate=null,"throw"===c&&a.iterator.return&&(b.method="return",b.arg=h,m(a,b),"throw"===b.method)||"return"!==c&&(b.method=
"throw",b.arg=new TypeError("The iterator does not provide a '"+c+"' method")),F;c=e(d,a.iterator,b.arg);return"throw"===c.type?(b.method="throw",b.arg=c.arg,b.delegate=null,F):(c=c.arg)?c.done?(b[a.resultName]=c.value,b.next=a.nextLoc,"return"!==b.method&&(b.method="next",b.arg=h),b.delegate=null,F):c:(b.method="throw",b.arg=new TypeError("iterator result is not an object"),b.delegate=null,F)}function da(a){var b={tryLoc:a[0]};1 in a&&(b.catchLoc=a[1]);2 in a&&(b.finallyLoc=a[2],b.afterLoc=a[3]);
this.tryEntries.push(b)}function r(a){var b=a.completion||{};b.type="normal";delete b.arg;a.completion=b}function p(a){this.tryEntries=[{tryLoc:"root"}];a.forEach(da,this);this.reset(!0)}function t(a){if(a||""===a){var b=a[J];if(b)return b.call(a);if("function"==typeof a.next)return a;if(!isNaN(a.length)){var c=-1;b=function E(){for(;++c<a.length;)if(u.call(a,c))return E.value=a[c],E.done=!1,E;return E.value=h,E.done=!0,E};return b.next=b}}throw new TypeError(q(a)+" is not iterable");}Y=function(){return A};
var h,A={},x=Object.prototype,u=x.hasOwnProperty,w=Object.defineProperty||function(a,b,c){a[b]=c.value},v="function"==typeof Symbol?Symbol:{},J=v.iterator||"@@iterator",D=v.asyncIterator||"@@asyncIterator",B=v.toStringTag||"@@toStringTag";try{a({},"")}catch(n){a=function(a,b,c){return a[b]=c}}A.wrap=b;var C="suspendedStart",H="suspendedYield",G="executing",z="completed",F={};v={};a(v,J,function(){return this});var M=Object.getPrototypeOf;(M=M&&M(M(t([]))))&&M!==x&&u.call(M,J)&&(v=M);var y=k.prototype=
c.prototype=Object.create(v);return d.prototype=k,w(y,"constructor",{value:k,configurable:!0}),w(k,"constructor",{value:d,configurable:!0}),d.displayName=a(k,B,"GeneratorFunction"),A.isGeneratorFunction=function(a){a="function"==typeof a&&a.constructor;return!!a&&(a===d||"GeneratorFunction"===(a.displayName||a.name))},A.mark=function(b){return Object.setPrototypeOf?Object.setPrototypeOf(b,k):(b.__proto__=k,a(b,B,"GeneratorFunction")),b.prototype=Object.create(y),b},A.awrap=function(a){return{__await:a}},
f(l.prototype),a(l.prototype,D,function(){return this}),A.AsyncIterator=l,A.async=function(a,c,d,e,k){void 0===k&&(k=g);var n=new l(b(a,c,d,e),k);return A.isGeneratorFunction(c)?n:n.next().then(function(a){return a.done?a.value:n.next()})},f(y),a(y,B,"Generator"),a(y,J,function(){return this}),a(y,"toString",function(){return"[object Generator]"}),A.keys=function(a){var b=Object(a),c=[],d;for(d in b)c.push(d);return c.reverse(),function T(){for(;c.length;){var a=c.pop();if(a in b)return T.value=a,
T.done=!1,T}return T.done=!0,T}},A.values=t,p.prototype={constructor:p,reset:function(a){if(this.prev=0,this.next=0,this.sent=this._sent=h,this.done=!1,this.delegate=null,this.method="next",this.arg=h,this.tryEntries.forEach(r),!a)for(var b in this)"t"===b.charAt(0)&&u.call(this,b)&&!isNaN(+b.slice(1))&&(this[b]=h)},stop:function(){this.done=!0;var a=this.tryEntries[0].completion;if("throw"===a.type)throw a.arg;return this.rval},dispatchException:function(a){function b(b,d){return k.type="throw",
k.arg=a,c.next=b,d&&(c.method="next",c.arg=h),!!d}if(this.done)throw a;for(var c=this,d=this.tryEntries.length-1;0<=d;--d){var e=this.tryEntries[d],k=e.completion;if("root"===e.tryLoc)return b("end");if(e.tryLoc<=this.prev){var n=u.call(e,"catchLoc"),f=u.call(e,"finallyLoc");if(n&&f){if(this.prev<e.catchLoc)return b(e.catchLoc,!0);if(this.prev<e.finallyLoc)return b(e.finallyLoc)}else if(n){if(this.prev<e.catchLoc)return b(e.catchLoc,!0)}else{if(!f)throw Error("try statement without catch or finally");
if(this.prev<e.finallyLoc)return b(e.finallyLoc)}}}},abrupt:function(a,b){for(var c=this.tryEntries.length-1;0<=c;--c){var d=this.tryEntries[c];if(d.tryLoc<=this.prev&&u.call(d,"finallyLoc")&&this.prev<d.finallyLoc){var e=d;break}}e&&("break"===a||"continue"===a)&&e.tryLoc<=b&&b<=e.finallyLoc&&(e=null);c=e?e.completion:{};return c.type=a,c.arg=b,e?(this.method="next",this.next=e.finallyLoc,F):this.complete(c)},complete:function(a,b){if("throw"===a.type)throw a.arg;return"break"===a.type||"continue"===
a.type?this.next=a.arg:"return"===a.type?(this.rval=this.arg=a.arg,this.method="return",this.next="end"):"normal"===a.type&&b&&(this.next=b),F},finish:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.finallyLoc===a)return this.complete(c.completion,c.afterLoc),r(c),F}},catch:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.tryLoc===a){a=c.completion;if("throw"===a.type){var d=a.arg;r(c)}return d}}throw Error("illegal catch attempt");
},delegateYield:function(a,b,c){return this.delegate={iterator:t(a),resultName:b,nextLoc:c},"next"===this.method&&(this.arg=h),F}},A}function ea(a,b,d,c,f,k,l){try{var e=a[k](l),K=e.value}catch(ka){return void d(ka)}e.done?b(K):g.resolve(K).then(c,f)}function J(){var a;return a=Y().mark(function aa(a,c){var d,e,f=arguments;return Y().wrap(function(k){for(;;)switch(k.prev=k.next){case 0:d=2<f.length&&void 0!==f[2]?f[2]:3,e=0;case 2:return k.prev=2,k.next=5,a(c);case 5:return k.abrupt("return",k.sent);
case 8:if(k.prev=8,k.t0=k.catch(2),!(++e>=d)){k.next=13;break}throw k.t0;case 13:return k.next=15,new g(function(a){return setTimeout(a,100)});case 15:if(e<d){k.next=2;break}case 16:case "end":return k.stop()}},aa,null,[[2,8]])}),J=function(){var d=this,c=arguments;return new g(function(e,k){function f(a){ea(l,e,k,f,g,"next",a)}function g(a){ea(l,e,k,f,g,"throw",a)}var l=a.apply(d,c);f(void 0)})},J.apply(this,arguments)}function fa(a,b,d,c){var e=b.appName;return function(a,b){return J.apply(this,
arguments)}(a,c,4<arguments.length&&void 0!==arguments[4]?arguments[4]:3).then(function(a){return b.emitCount(m(e,l.SERVICE,x(null==c?void 0:c.metricDimensions),d)),a}).catch(function(a){throw b.emitCount(m(e,l.SERVICE,d,l.ERROR)),new Z("failed to ".concat(d.toLowerCase()," consent for ").concat(e),a);})}function ma(a,b,d,c){var e=b||na,k=d||oa;return c&&ha.adaptiveBackoff.updateConfig(c),{prompt:function(){return function(a,b,c){var d=b.appName;return function(a,b){var c;a=H(a,b);return Date.now()>
(null!==(c=a.defer)&&void 0!==c?c:0)}(c,b)?a().then(function(a){return b.emitCount(m(d,l.SERVICE,x(null==a?void 0:a.metricDimensions),l.PROMPT)),S(c,b),a}).catch(function(a){var e,k=a.status||(null===(e=a.http)||void 0===e?void 0:e.status)||0;if(429!==k&&204!==k)throw b.emitCount(m(d,l.SERVICE,l.PROMPT,l.ERROR)),new Z("failed to prompt for consent for "+d,a);a=H(c,b);U(c,{principal:a.principal,prompts:a.prompts,defer:Date.now()+Q.writeCooldownDuration*X},b);!0}):function(a){return new g(function(b){a.emitCount(m(a.appName,
l.SERVICE,l.PROMPT,l.SKIP));b(null)})}(b)}(a.prompt,e,k)},accept:function(b){return fa(a.accept,e,l.ACCEPT,b)},decline:function(b){return fa(a.decline,e,l.DECLINE,b)},customize:function(b){return function(a,b,c){var d=b.appName;return a(c).then(function(a){return b.emitCount(m(d,l.SERVICE,x(null==c?void 0:c.metricDimensions),l.CUSTOMIZE)),a}).catch(function(a){throw b.emitCount(m(d,l.SERVICE,l.CUSTOMIZE,l.ERROR)),new Z("failed to customize consent for "+d,a);})}(a.customize,e,b)}}}var W={d:function(a,
b){for(var d in b)W.o(b,d)&&!W.o(a,d)&&Object.defineProperty(a,d,{enumerable:!0,get:b[d]})},o:function(a,b){return Object.prototype.hasOwnProperty.call(a,b)},r:function(a){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});Object.defineProperty(a,"__esModule",{value:!0})}},B={};W.r(B);W.d(B,{initialize:function(){return ma}});var l=function(a){return a.SERVICE="cos",a.PROMPT="prompt",a.ACCEPT="accept",a.DECLINE="decline",a.CUSTOMIZE="customize",
a.STORE="store",a.READ="read",a.WRITE="write",a.ERROR="error",a.SKIP="skip",a}({}),na={appName:"unknown",emitCount:function(a,b){},emitTiming:function(a,b){}},ha={adaptiveBackoff:new (function(){return a=function c(){if(!(this instanceof c))throw new TypeError("Cannot call a class as a function");!0;G(this,"_promptsUntilCooldown",5);G(this,"_promptTimeWindow",10);G(this,"_readCooldownDuration",15);G(this,"_writeCooldownDuration",1440)},b=[{key:"promptsUntilCooldown",get:function(){return this._promptsUntilCooldown},
set:function(a){this._promptsUntilCooldown=a}},{key:"promptTimeWindow",get:function(){return this._promptTimeWindow},set:function(a){this._promptTimeWindow=a}},{key:"readCooldownDuration",get:function(){return this._readCooldownDuration},set:function(a){this._readCooldownDuration=a}},{key:"writeCooldownDuration",get:function(){return this._writeCooldownDuration},set:function(a){this._writeCooldownDuration=a}},{key:"updateConfig",value:function(a){this._promptsUntilCooldown=a.promptsUntilCooldown;
this._promptTimeWindow=a.promptTimeWindow;this._readCooldownDuration=a.readCooldownDuration;this._writeCooldownDuration=a.writeCooldownDuration}},{key:"getConfig",value:function(){return{promptsUntilCooldown:this._promptsUntilCooldown,promptTimeWindow:this._promptTimeWindow,readCooldownDuration:this._readCooldownDuration,writeCooldownDuration:this._writeCooldownDuration}}}],ia(a.prototype,b),Object.defineProperty(a,"prototype",{writable:!1}),a;var a,b}())},Q=ha.adaptiveBackoff,X=6E4,ca="sp-cc-pcl",
oa={id:function(){return"unknown"},set:function(a,b){},get:function(a){return""}},Z=function(a){function b(a,d){if(!(this instanceof b))throw new TypeError("Cannot call a class as a function");var c=b;var e=[a];c=f(c);c=D()?Reflect.construct(c,e||[],f(this).constructor):c.apply(this,e);if(!c||"object"!=z(c)&&"function"!=typeof c){if(void 0!==c)throw new TypeError("Derived constructors may only return object or undefined");if(void 0===this)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");
c=this}return c.message=a,c.cause=d,c.cause=d,c.name="ConsentOrchestrationError",Object.setPrototypeOf(c,b.prototype),c}return function(a,b){if("function"!=typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function");a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,writable:!0,configurable:!0}});Object.defineProperty(a,"prototype",{writable:!1});b&&d(a,b)}(b,a),e=b,Object.defineProperty(e,"prototype",{writable:!1}),e;var e}(y(Error));p=B})();return p});
"use strict";u.when("A","3p-promise","a-util","@amzn/consent-orchestration-client-sdk","ready").execute("centralized-prompting",function(g,t,I,N){var m,x,h=function(){},B={0:(m={name:"cc.banner"},p(m,"NO_VALUE","bannerPopUp"),p(m,"REJECT_ALL",".rejectall.linkbutton"),m),4:{name:"ads.banner"},5:{name:"datashare.banner"},21:{name:"3p.banner"},42:{name:"quebec.banner"}},G=(x={},p(x,"NO_VALUE",".popup"),p(x,"ACCEPT_ALL",".acceptAll"),p(x,"REJECT_ALL",".rejectall"),p(x,"ACCEPT_PARTIAL",".customize"),x),
O=function(d){return new t(function(f,q){g.post("/privacyprefs/retail/v3/banner",{params:{consent:d.payload.url,consentTypes:d.consentTypes},paramsFormat:"json",accepts:"application/json",contentType:"application/json",timeout:5E3,headers:{"anti-csrftoken-a2z":d.csrfToken},success:function(d){f(d)},error:function(d){q(d)}})})},P=["x-acb","x-main","x-tacb"],ja=function(){return r.fwcimData&&fwcimData.customerId||Object.keys(I.cookies.getAll()||{}).some(function(d){return P.some(function(f){return d.startsWith(f)})})?
"1":"0"},w=g.capabilities.localStorage?localStorage:{getItem:function(d){return null},setItem:h,removeItem:h};m=r.ue&&"function"===typeof ue.count?function(d){return ue.count(d,1)}:h;var v=r.uet&&r.uex?{start:function(){return uet("bb","centralizedConsentBanner",{wb:1})},stop:function(){return uex("ld","centralizedConsentBanner",{wb:1})}}:{start:h,stop:h};v.start();var R=function(){return["[^\x26]*\\/prime\\/offer\\/[^\x26\\/]+\\/prime-deal.*"].some(function(d){return r.location.href.match(d)})},
C=N.initialize({prompt:function(){return new t(function(d,f){g.get("/privacyprefs/retail/v3/banner",{success:function(q){q||f(Error("No Data"));var h=document.createElement("div");h.id="sp-cc-wrapper";h.innerHTML=q;q=h.querySelector('input[type\x3d"hidden"][name\x3d"disclosureDecision"]');h={banner:h,metricDimensions:[q?q.value:"unknown"]};w.getItem("sp-cc-pending")&&(q=h.banner.querySelector("#sp-cc-error"))&&(q.className=(" "+q.className+" ").replace(" aok-hidden "," "));w.removeItem("sp-cc-pending");
U(h.banner);D(g.$("#cos-banner"),"NO_VALUE");d(h)},error:function(d){f(d)}})})},accept:function(d){return O(d)},decline:function(d){return O(d)},customize:function(d){return new t(function(f){f(d)})}},{appName:"sp",emitCount:m,emitTiming:h},{id:function(){var d=I.cookies.get("session-id")+"|"+ja();return r.fwcimData&&fwcimData.customerId?d+"|"+fwcimData.customerId:d},get:function(d){if(!R())return w.getItem(d)},set:function(d,f){R()||w.setItem(d,f)}},{promptsUntilCooldown:5,promptTimeWindow:10,readCooldownDuration:15,
writeCooldownDuration:1440}),S=void 0,H=function(){var d=g.$("#cos-banner").outerHeight();"number"!==typeof d||0>=d?document.querySelector("html").style.removeProperty("scroll-padding-bottom"):(d+="px",g.capabilities.mobile?document.querySelector("#a-page").style.marginBottom=d:document.body.style.paddingBottom=d,document.querySelector("html").style.setProperty("scroll-padding-bottom",d))},U=function(d){var f=g.$("#a-page \x3e *:not(script)").first();f.length?f.before(d):document.body.appendChild(d);
u.when("a-expander").execute(function(d){d.initializeExpanders()})};C.prompt().then(function(){v.stop();S=g.on("orientationchange resize",H);H()}).catch(function(d){v.stop();throw d;});var z=function(){g.$("#sp-cc-wrapper").remove();w.setItem("sp-cc-pending","1");S&&g.off(S);H()},y=function(d,f){f.$event.preventDefault();var g=d.find('[name\x3d"anti-csrftoken-a2z"]'),h=d.find('[name\x3d"disclosureDecision"]');d=d.find('[name\x3d"consentTypes"]').val();return{payload:f.data,csrfToken:g.val(),metricDimensions:[h.val()],
consentTypes:d}};g.declarative("banner-accept-all","click",function(d){var f=g.$("#cos-banner");d=y(f,d);z();C.accept(d).then(function(){w.removeItem("sp-cc-pending");D(f,"ACCEPT_ALL")})});g.declarative("banner-reject-all","click",function(d){var f=g.$("#cos-banner");d=y(f,d);z();C.decline(d).then(function(){w.removeItem("sp-cc-pending");D(f,"REJECT_ALL")})});g.declarative("banner-customize","click",function(){var d=g.$("#cos-banner"),f=d.find('[name\x3d"disclosureDecision"]');C.customize({metricDimensions:[f.val()]}).then(function(){D(d,
"ACCEPT_PARTIAL")})});var D=function(d,f){var h=d.find('[name\x3d"consentTypes"]').val();h&&""!==h.trim()&&0!==h.length&&(h=h.split(","),g.each(h,function(h){if(B.hasOwnProperty(h)&&r.csa&&"function"===typeof r.csa){var p=csa("Events",{producerId:"cdo-privacy"}),m=B[h],t="NO_VALUE"===f,q=m.hasOwnProperty(f)?m[f]:G[f];m=g.contains(q,".")?m.name+q:q;p("log",{schemaId:"cdo_privacy.anonymia.consent_business_metrics.6",producerId:"cdo-privacy",aaaClientName:"ShoppingPortal",consentType:h,consentValue:m,
consentInferredValue:f,consentAdditionalAttribute:"null",clientType:d.find('[name\x3d"clientType"]').val(),privacyCustomerId:d.find('[name\x3d"privacyCustomerId"]').val(),sessionId:d.find('[name\x3d"sessionId"]').val(),userType:d.find('[name\x3d"userType"]').val(),businessDomain:"1",userId:d.find('[name\x3d"userId"]').val(),tollhouseMarketplaceId:"null",uiEventSource:d.find('input[type\x3d"hidden"][name\x3d"disclosureDecision"]').val(),uiEventActionType:t?"bannerPopUp":"buttonClick"})}}))}})});